apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: infra
  name: fluentd
  labels:
    app-name: fluentd

spec:
  template:
    metadata:
      labels:
        name: fluentd

    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always

      containers:
        - name: fluentd
          image: gcr.io/google_containers/fluentd-elasticsearch:1.15
          resources:
                  requests:
                    cpu: 200m
                    memory: 300Mi
                  limits:
                    cpu: 1000m
                    memory: 1000Mi
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: config
            mountPath: /etc/td-agent
            readOnly: true

      terminationGracePeriodSeconds: 1
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: fluentd
