apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: infra
  name: vip-192-16-239-53
  labels:
    app-name: vip-192-16-239-53

spec:
  template:
    metadata:
      labels:
        name: vip-192-16-239-53

    spec:
      nodeSelector:
        zone: fe-prod

      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

      containers:
        - name: keepalived-vip
          image: oberthur/docker-keepalived:20160917
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              cpu: 30m
              memory: 32Mi
            limits:
              cpu: 1
              memory: 48Mi
          env:
            - name: VIP
              value: "192.16.239.53"
            - name: MASK
              value: "32"
            - name: VROUTERID
              value: "53"
            - name: STATE
              value: "BACKUP"
            - name: INTERFACE
              value: "eth0"
            - name: PRIORITY
              value: "100"
            - name: ADVERT
              value: "1"
            - name: AUTHPASS
              value: ohCheiteiphoWoo8
